import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import StartingForm from '@/components/starting-form/starting-form'

export default function Home() {
  const greeting = 'Welcome to Tic-Tac-Toe game!'

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            {greeting}
          </p>

          <StartingForm />
        </div>
      </main>
    </>
  )
}
